server:
  port: 8080

spring:
  application:
    name: voting-api
  liquibase:
    change-log: classpath:/dbchangelog.yml
  datasource:
    url: jdbc:mariadb://localhost:3306/voting_app_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      dll-auto: validate
      show-sql: true